/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "e42ap_v3_01.asn"
 * 	`asn1c -gen-APER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#include "ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using RICaction_ToBeSetup_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_Admitted_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_NotAdmitted_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscription_withCause_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeRemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeAddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeRemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_AddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeAddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RequiredToBeModified_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RequiredToBeRemoved_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ConfirmedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RefusedToBeModified_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ConfirmedForRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RefusedToBeRemoved_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionUpdate_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionUpdateRemove_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionSetupFailed_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigAddition_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigUpdate_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeTNLassociationRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigAdditionAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigUpdateAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigRemovalAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunction_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionID_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionIDcause_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P0_e2ap_v3_01_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P0_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P0_e2ap_v3_01_tags_1,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P0_e2ap_v3_01_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P0_e2ap_v3_01_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P0_e2ap_v3_01_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P0_e2ap_v3_01_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P0_e2ap_v3_01_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_ToBeSetup_ItemIEs_1_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeSetup_ItemIEs_specs_1_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_01_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_01_tags_2,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_01_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_01_tags_2[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_01_tags_2,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_01_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_01_tags_2[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_Admitted_ItemIEs_5_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_Admitted_ItemIEs_specs_5_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_01_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_01_tags_3,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_01_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_01_tags_3[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_01_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_01_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_01_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_NotAdmitted_ItemIEs_9_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_NotAdmitted_ItemIEs_specs_9_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_01_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_01_tags_4,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_01_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_01_tags_4[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_01_tags_4,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_01_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_01_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICsubscription_withCause_ItemIEs_13_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICsubscription_withCause_ItemIEs_specs_13_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P4_e2ap_v3_01_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P4_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P4_e2ap_v3_01_tags_5,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P4_e2ap_v3_01_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P4_e2ap_v3_01_tags_5[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P4_e2ap_v3_01_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P4_e2ap_v3_01_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P4_e2ap_v3_01_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_ToBeRemovedForModification_ItemIEs_17_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeRemovedForModification_ItemIEs_specs_17_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P5_e2ap_v3_01_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P5_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P5_e2ap_v3_01_tags_6,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P5_e2ap_v3_01_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P5_e2ap_v3_01_tags_6[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P5_e2ap_v3_01_tags_6,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P5_e2ap_v3_01_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P5_e2ap_v3_01_tags_6[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_ToBeModifiedForModification_ItemIEs_21_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeModifiedForModification_ItemIEs_specs_21_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P6_e2ap_v3_01_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P6_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P6_e2ap_v3_01_tags_7,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P6_e2ap_v3_01_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P6_e2ap_v3_01_tags_7[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P6_e2ap_v3_01_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P6_e2ap_v3_01_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P6_e2ap_v3_01_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_ToBeAddedForModification_ItemIEs_25_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeAddedForModification_ItemIEs_specs_25_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P7_e2ap_v3_01_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P7_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P7_e2ap_v3_01_tags_8,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P7_e2ap_v3_01_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P7_e2ap_v3_01_tags_8[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P7_e2ap_v3_01_tags_8,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P7_e2ap_v3_01_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P7_e2ap_v3_01_tags_8[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_RemovedForModification_ItemIEs_29_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_RemovedForModification_ItemIEs_specs_29_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P8_e2ap_v3_01_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P8_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P8_e2ap_v3_01_tags_9,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P8_e2ap_v3_01_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P8_e2ap_v3_01_tags_9[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P8_e2ap_v3_01_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P8_e2ap_v3_01_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P8_e2ap_v3_01_tags_9[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_FailedToBeRemovedForModification_ItemIEs_33_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeRemovedForModification_ItemIEs_specs_33_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P9_e2ap_v3_01_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P9_e2ap_v3_01 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P9_e2ap_v3_01_tags_10,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P9_e2ap_v3_01_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P9_e2ap_v3_01_tags_10[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P9_e2ap_v3_01_tags_10,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P9_e2ap_v3_01_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P9_e2ap_v3_01_tags_10[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_ModifiedForModification_ItemIEs_37_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_ModifiedForModification_ItemIEs_specs_37_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_010_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_010 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_010_tags_11,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_010_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_010_tags_11[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_010_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_010_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_010_tags_11[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_FailedToBeModifiedForModification_ItemIEs_41_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeModifiedForModification_ItemIEs_specs_41_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_011_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_011 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_011_tags_12,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_011_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_011_tags_12[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_011_tags_12,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_011_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_011_tags_12[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_AddedForModification_ItemIEs_45_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_AddedForModification_ItemIEs_specs_45_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_012_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_012 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_012_tags_13,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_012_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_012_tags_13[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_012_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_012_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_012_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_FailedToBeAddedForModification_ItemIEs_49_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeAddedForModification_ItemIEs_specs_49_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_013_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_013 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_013_tags_14,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_013_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_013_tags_14[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_013_tags_14,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_013_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_013_tags_14[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_RequiredToBeModified_ItemIEs_53_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_RequiredToBeModified_ItemIEs_specs_53_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_014_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_014 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_014_tags_15,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_014_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_014_tags_15[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_014_tags_15,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_014_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_014_tags_15[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_RequiredToBeRemoved_ItemIEs_57_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_RequiredToBeRemoved_ItemIEs_specs_57_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_015_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_015 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_015_tags_16,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_015_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_015_tags_16[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_015_tags_16,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_015_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_015_tags_16[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_ConfirmedForModification_ItemIEs_61_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_ConfirmedForModification_ItemIEs_specs_61_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_016_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_016 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_016_tags_17,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_016_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_016_tags_17[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_016_tags_17,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_016_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_016_tags_17[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_RefusedToBeModified_ItemIEs_65_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_RefusedToBeModified_ItemIEs_specs_65_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_017_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_017 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_017_tags_18,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_017_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_017_tags_18[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_017_tags_18,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_017_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_017_tags_18[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_ConfirmedForRemoval_ItemIEs_69_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_ConfirmedForRemoval_ItemIEs_specs_69_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_018_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_018 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_018_tags_19,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_018_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_018_tags_19[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_018_tags_19,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_018_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_018_tags_19[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_RefusedToBeRemoved_ItemIEs_73_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RICaction_RefusedToBeRemoved_ItemIEs_specs_73_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_019_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_019 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_019_tags_20,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_019_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_019_tags_20[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_019_tags_20,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_019_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P1_e2ap_v3_019_tags_20[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2connectionUpdate_ItemIEs_77_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2connectionUpdate_ItemIEs_specs_77_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_010_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_010 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_010_tags_21,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_010_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_010_tags_21[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_010_tags_21,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_010_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_010_tags_21[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2connectionUpdateRemove_ItemIEs_81_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2connectionUpdateRemove_ItemIEs_specs_81_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_011_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_011 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_011_tags_22,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_011_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_011_tags_22[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_011_tags_22,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_011_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_011_tags_22[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2connectionSetupFailed_ItemIEs_85_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2connectionSetupFailed_ItemIEs_specs_85_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_012_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_012 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_012_tags_23,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_012_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_012_tags_23[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_012_tags_23,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_012_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_012_tags_23[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2nodeComponentConfigAddition_ItemIEs_89_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigAddition_ItemIEs_specs_89_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_013_tags_24[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_013 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_013_tags_24,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_013_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_013_tags_24[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_013_tags_24,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_013_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_013_tags_24[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2nodeComponentConfigUpdate_ItemIEs_93_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigUpdate_ItemIEs_specs_93_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_014_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_014 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_014_tags_25,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_014_tags_25)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_014_tags_25[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_014_tags_25,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_014_tags_25)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_014_tags_25[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2nodeComponentConfigRemoval_ItemIEs_97_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigRemoval_ItemIEs_specs_97_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_015_tags_26[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_015 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_015_tags_26,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_015_tags_26)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_015_tags_26[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_015_tags_26,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_015_tags_26)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_015_tags_26[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2nodeTNLassociationRemoval_ItemIEs_101_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2nodeTNLassociationRemoval_ItemIEs_specs_101_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_016_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_016 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_016_tags_27,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_016_tags_27)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_016_tags_27[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_016_tags_27,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_016_tags_27)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_016_tags_27[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2nodeComponentConfigAdditionAck_ItemIEs_105_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigAdditionAck_ItemIEs_specs_105_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_017_tags_28[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_017 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_017_tags_28,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_017_tags_28)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_017_tags_28[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_017_tags_28,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_017_tags_28)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_017_tags_28[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2nodeComponentConfigUpdateAck_ItemIEs_109_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigUpdateAck_ItemIEs_specs_109_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_018_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_018 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_018_tags_29,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_018_tags_29)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_018_tags_29[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_018_tags_29,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_018_tags_29)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_018_tags_29[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_E2nodeComponentConfigRemovalAck_ItemIEs_113_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigRemovalAck_ItemIEs_specs_113_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_019_tags_30[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_019 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_019_tags_30,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_019_tags_30)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_019_tags_30[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_019_tags_30,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_019_tags_30)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P2_e2ap_v3_019_tags_30[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RANfunction_ItemIEs_117_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RANfunction_ItemIEs_specs_117_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_010_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_010 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_010_tags_31,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_010_tags_31)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_010_tags_31[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_010_tags_31,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_010_tags_31)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_010_tags_31[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RANfunctionID_ItemIEs_121_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RANfunctionID_ItemIEs_specs_121_e2ap_v3_01	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_011_tags_32[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_011 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_011_tags_32,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_011_tags_32)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_011_tags_32[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_011_tags_32,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_011_tags_32)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_2694P3_e2ap_v3_011_tags_32[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RANfunctionIDcause_ItemIEs_125_e2ap_v3_01,
	3,	/* Elements count */
	&asn_SPC_RANfunctionIDcause_ItemIEs_specs_125_e2ap_v3_01	/* Additional specs */
};

