/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "e42ap_v3_01.asn"
 * 	`asn1c -gen-APER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#ifndef	_RICactionExecutionOrder_H_
#define	_RICactionExecutionOrder_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RICactionExecutionOrder */
typedef long	 RICactionExecutionOrder_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RICactionExecutionOrder_constr_1_e2ap_v3_01;
extern asn_TYPE_descriptor_t asn_DEF_RICactionExecutionOrder_e2ap_v3_01;
asn_struct_free_f RICactionExecutionOrder_free;
asn_struct_print_f RICactionExecutionOrder_print;
asn_constr_check_f RICactionExecutionOrder_constraint_e2ap_v3_01;
ber_type_decoder_f RICactionExecutionOrder_decode_ber;
der_type_encoder_f RICactionExecutionOrder_encode_e2ap_v3_01_der;
xer_type_decoder_f RICactionExecutionOrder_decode_xer;
xer_type_encoder_f RICactionExecutionOrder_encode_e2ap_v3_01_xer;
jer_type_encoder_f RICactionExecutionOrder_encode_e2ap_v3_01_jer;
per_type_decoder_f RICactionExecutionOrder_decode_uper;
per_type_encoder_f RICactionExecutionOrder_encode_e2ap_v3_01_uper;
per_type_decoder_f RICactionExecutionOrder_decode_aper;
per_type_encoder_f RICactionExecutionOrder_encode_e2ap_v3_01_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICactionExecutionOrder_H_ */
#include <asn_internal.h>
