/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "e42ap_v3_01.asn"
 * 	`asn1c -gen-APER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#include "RICaction-ToBeAddedForModification-Item.h"

#include "RICsubsequentAction.h"
asn_TYPE_member_t asn_MBR_RICaction_ToBeAddedForModification_Item_1_e2ap_v3_01[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RICaction_ToBeAddedForModification_Item, ricActionID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICactionID_e2ap_v3_01,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricActionID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RICaction_ToBeAddedForModification_Item, ricActionType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICactionType_e2ap_v3_01,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricActionType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RICaction_ToBeAddedForModification_Item, ricActionDefinition),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICactionDefinition_e2ap_v3_01,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricActionDefinition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RICaction_ToBeAddedForModification_Item, ricActionExecutionOrder),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICactionExecutionOrder_e2ap_v3_01,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricActionExecutionOrder"
		},
	{ ATF_POINTER, 1, offsetof(struct RICaction_ToBeAddedForModification_Item, ricSubsequentAction),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICsubsequentAction_e2ap_v3_01,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricSubsequentAction"
		},
};
static const int asn_MAP_RICaction_ToBeAddedForModification_Item_oms_1_e2ap_v3_01[] = { 4 };
static const ber_tlv_tag_t asn_DEF_RICaction_ToBeAddedForModification_Item_e2ap_v3_01_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RICaction_ToBeAddedForModification_Item_tag2el_1_e2ap_v3_01[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ricActionID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ricActionType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ricActionDefinition */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ricActionExecutionOrder */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ricSubsequentAction */
};
asn_SEQUENCE_specifics_t asn_SPC_RICaction_ToBeAddedForModification_Item_specs_1_e2ap_v3_01 = {
	sizeof(struct RICaction_ToBeAddedForModification_Item),
	offsetof(struct RICaction_ToBeAddedForModification_Item, _asn_ctx),
	asn_MAP_RICaction_ToBeAddedForModification_Item_tag2el_1_e2ap_v3_01,
	5,	/* Count of tags in the map */
	asn_MAP_RICaction_ToBeAddedForModification_Item_oms_1_e2ap_v3_01,	/* Optional members */
	1, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RICaction_ToBeAddedForModification_Item_e2ap_v3_01 = {
	"RICaction-ToBeAddedForModification-Item",
	"RICaction-ToBeAddedForModification-Item",
	&asn_OP_SEQUENCE_e2ap_v3_01,
	asn_DEF_RICaction_ToBeAddedForModification_Item_e2ap_v3_01_tags_1,
	sizeof(asn_DEF_RICaction_ToBeAddedForModification_Item_e2ap_v3_01_tags_1)
		/sizeof(asn_DEF_RICaction_ToBeAddedForModification_Item_e2ap_v3_01_tags_1[0]), /* 1 */
	asn_DEF_RICaction_ToBeAddedForModification_Item_e2ap_v3_01_tags_1,	/* Same as above */
	sizeof(asn_DEF_RICaction_ToBeAddedForModification_Item_e2ap_v3_01_tags_1)
		/sizeof(asn_DEF_RICaction_ToBeAddedForModification_Item_e2ap_v3_01_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint_e2ap_v3_01
	},
	asn_MBR_RICaction_ToBeAddedForModification_Item_1_e2ap_v3_01,
	5,	/* Elements count */
	&asn_SPC_RICaction_ToBeAddedForModification_Item_specs_1_e2ap_v3_01	/* Additional specs */
};

