/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "e2ap-v01.01.asn1"
 * 	`asn1c -gen-APER -no-gen-JER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#include "ProtocolIE-Container.h"

#include "ProtocolIE-Field.h"
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P0_constr_1_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P1_constr_3_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P2_constr_5_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P3_constr_7_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P4_constr_9_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P5_constr_11_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P6_constr_13_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P7_constr_15_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P8_constr_17_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P9_constr_19_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P10_constr_21_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P11_constr_23_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P12_constr_25_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P13_constr_27_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P14_constr_29_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P15_constr_31_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P16_constr_33_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P17_constr_35_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P18_constr_37_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P19_constr_39_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P20_constr_41_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P21_constr_43_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P22_constr_45_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P23_constr_47_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P24_constr_49_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P25_constr_51_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P26_constr_53_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P27_constr_55_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P28_constr_57_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P29_constr_59_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P30_constr_61_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_1478P31_constr_63_e2ap_v1_01 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P0_1_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionRequest_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P0_e2ap_v1_01_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P0_specs_1_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P0),
	offsetof(struct ProtocolIE_Container_1478P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P0_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P0_e2ap_v1_01_tags_1,
	sizeof(asn_DEF_ProtocolIE_Container_1478P0_e2ap_v1_01_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P0_e2ap_v1_01_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P0_e2ap_v1_01_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P0_e2ap_v1_01_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P0_e2ap_v1_01_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P0_constr_1_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P0_1_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P0_specs_1_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P1_3_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionResponse_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_01_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P1_specs_3_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P1),
	offsetof(struct ProtocolIE_Container_1478P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_01_tags_3,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_01_tags_3)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_01_tags_3[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_01_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_01_tags_3)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_01_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P1_constr_3_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P1_3_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P1_specs_3_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P2_5_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionFailure_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_01_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P2_specs_5_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P2),
	offsetof(struct ProtocolIE_Container_1478P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_01_tags_5,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_01_tags_5)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_01_tags_5[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_01_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_01_tags_5)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_01_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P2_constr_5_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P2_5_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P2_specs_5_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P3_7_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42RICsubscriptionRequest_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_01_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P3_specs_7_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P3),
	offsetof(struct ProtocolIE_Container_1478P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_01_tags_7,
	sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_01_tags_7)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_01_tags_7[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_01_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_01_tags_7)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_01_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P3_constr_7_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P3_7_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P3_specs_7_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P4_9_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42RICsubscriptionDeleteRequest_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P4_e2ap_v1_01_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P4_specs_9_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P4),
	offsetof(struct ProtocolIE_Container_1478P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P4_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P4_e2ap_v1_01_tags_9,
	sizeof(asn_DEF_ProtocolIE_Container_1478P4_e2ap_v1_01_tags_9)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P4_e2ap_v1_01_tags_9[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P4_e2ap_v1_01_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P4_e2ap_v1_01_tags_9)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P4_e2ap_v1_01_tags_9[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P4_constr_9_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P4_9_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P4_specs_9_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P5_11_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteRequest_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P5_e2ap_v1_01_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P5_specs_11_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P5),
	offsetof(struct ProtocolIE_Container_1478P5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P5_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P5_e2ap_v1_01_tags_11,
	sizeof(asn_DEF_ProtocolIE_Container_1478P5_e2ap_v1_01_tags_11)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P5_e2ap_v1_01_tags_11[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P5_e2ap_v1_01_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P5_e2ap_v1_01_tags_11)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P5_e2ap_v1_01_tags_11[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P5_constr_11_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P5_11_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P5_specs_11_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P6_13_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteResponse_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P6_e2ap_v1_01_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P6_specs_13_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P6),
	offsetof(struct ProtocolIE_Container_1478P6, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P6_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P6_e2ap_v1_01_tags_13,
	sizeof(asn_DEF_ProtocolIE_Container_1478P6_e2ap_v1_01_tags_13)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P6_e2ap_v1_01_tags_13[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P6_e2ap_v1_01_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P6_e2ap_v1_01_tags_13)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P6_e2ap_v1_01_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P6_constr_13_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P6_13_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P6_specs_13_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P7_15_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteFailure_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P7_e2ap_v1_01_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P7_specs_15_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P7),
	offsetof(struct ProtocolIE_Container_1478P7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P7_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P7_e2ap_v1_01_tags_15,
	sizeof(asn_DEF_ProtocolIE_Container_1478P7_e2ap_v1_01_tags_15)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P7_e2ap_v1_01_tags_15[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P7_e2ap_v1_01_tags_15,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P7_e2ap_v1_01_tags_15)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P7_e2ap_v1_01_tags_15[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P7_constr_15_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P7_15_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P7_specs_15_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P8_17_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICindication_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P8_e2ap_v1_01_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P8_specs_17_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P8),
	offsetof(struct ProtocolIE_Container_1478P8, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P8_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P8_e2ap_v1_01_tags_17,
	sizeof(asn_DEF_ProtocolIE_Container_1478P8_e2ap_v1_01_tags_17)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P8_e2ap_v1_01_tags_17[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P8_e2ap_v1_01_tags_17,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P8_e2ap_v1_01_tags_17)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P8_e2ap_v1_01_tags_17[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P8_constr_17_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P8_17_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P8_specs_17_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P9_19_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolRequest_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P9_e2ap_v1_01_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P9_specs_19_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P9),
	offsetof(struct ProtocolIE_Container_1478P9, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P9_e2ap_v1_01 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P9_e2ap_v1_01_tags_19,
	sizeof(asn_DEF_ProtocolIE_Container_1478P9_e2ap_v1_01_tags_19)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P9_e2ap_v1_01_tags_19[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P9_e2ap_v1_01_tags_19,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P9_e2ap_v1_01_tags_19)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P9_e2ap_v1_01_tags_19[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P9_constr_19_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P9_19_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P9_specs_19_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P10_21_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42RICcontrolRequest_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_010_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P10_specs_21_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P10),
	offsetof(struct ProtocolIE_Container_1478P10, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_010 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_010_tags_21,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_010_tags_21)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_010_tags_21[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_010_tags_21,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_010_tags_21)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_010_tags_21[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P10_constr_21_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P10_21_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P10_specs_21_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P11_23_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolAcknowledge_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_011_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P11_specs_23_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P11),
	offsetof(struct ProtocolIE_Container_1478P11, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_011 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_011_tags_23,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_011_tags_23)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_011_tags_23[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_011_tags_23,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_011_tags_23)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_011_tags_23[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P11_constr_23_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P11_23_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P11_specs_23_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P12_25_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolFailure_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_012_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P12_specs_25_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P12),
	offsetof(struct ProtocolIE_Container_1478P12, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_012 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_012_tags_25,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_012_tags_25)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_012_tags_25[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_012_tags_25,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_012_tags_25)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_012_tags_25[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P12_constr_25_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P12_25_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P12_specs_25_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P13_27_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ErrorIndication_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_013_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P13_specs_27_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P13),
	offsetof(struct ProtocolIE_Container_1478P13, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_013 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_013_tags_27,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_013_tags_27)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_013_tags_27[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_013_tags_27,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_013_tags_27)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_013_tags_27[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P13_constr_27_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P13_27_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P13_specs_27_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P14_29_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupRequest_e2ap_v1_01IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_014_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P14_specs_29_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P14),
	offsetof(struct ProtocolIE_Container_1478P14, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_014 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_014_tags_29,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_014_tags_29)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_014_tags_29[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_014_tags_29,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_014_tags_29)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_014_tags_29[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P14_constr_29_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P14_29_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P14_specs_29_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P15_31_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42setupRequest_e2ap_v1_01IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_015_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P15_specs_31_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P15),
	offsetof(struct ProtocolIE_Container_1478P15, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_015 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_015_tags_31,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_015_tags_31)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_015_tags_31[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_015_tags_31,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_015_tags_31)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_015_tags_31[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P15_constr_31_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P15_31_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P15_specs_31_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P16_33_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupResponse_e2ap_v1_01IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_016_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P16_specs_33_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P16),
	offsetof(struct ProtocolIE_Container_1478P16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_016 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_016_tags_33,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_016_tags_33)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_016_tags_33[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_016_tags_33,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_016_tags_33)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_016_tags_33[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P16_constr_33_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P16_33_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P16_specs_33_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P17_35_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42setupResponse_e2ap_v1_01IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_017_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P17_specs_35_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P17),
	offsetof(struct ProtocolIE_Container_1478P17, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_017 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_017_tags_35,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_017_tags_35)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_017_tags_35[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_017_tags_35,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_017_tags_35)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_017_tags_35[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P17_constr_35_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P17_35_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P17_specs_35_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P18_37_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupFailure_e2ap_v1_01IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_018_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P18_specs_37_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P18),
	offsetof(struct ProtocolIE_Container_1478P18, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_018 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_018_tags_37,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_018_tags_37)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_018_tags_37[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_018_tags_37,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_018_tags_37)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_018_tags_37[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P18_constr_37_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P18_37_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P18_specs_37_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P19_39_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2connectionUpdate_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_019_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P19_specs_39_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P19),
	offsetof(struct ProtocolIE_Container_1478P19, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_019 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_019_tags_39,
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_019_tags_39)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_019_tags_39[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_019_tags_39,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_019_tags_39)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P1_e2ap_v1_019_tags_39[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P19_constr_39_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P19_39_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P19_specs_39_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P20_41_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2connectionUpdate_e2ap_v1_01Ack_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_010_tags_41[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P20_specs_41_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P20),
	offsetof(struct ProtocolIE_Container_1478P20, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_010 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_010_tags_41,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_010_tags_41)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_010_tags_41[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_010_tags_41,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_010_tags_41)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_010_tags_41[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P20_constr_41_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P20_41_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P20_specs_41_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P21_43_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2connectionUpdate_e2ap_v1_01Failure_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_011_tags_43[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P21_specs_43_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P21),
	offsetof(struct ProtocolIE_Container_1478P21, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_011 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_011_tags_43,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_011_tags_43)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_011_tags_43[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_011_tags_43,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_011_tags_43)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_011_tags_43[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P21_constr_43_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P21_43_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P21_specs_43_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P22_45_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2nodeConfigurationUpdate_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_012_tags_45[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P22_specs_45_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P22),
	offsetof(struct ProtocolIE_Container_1478P22, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_012 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_012_tags_45,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_012_tags_45)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_012_tags_45[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_012_tags_45,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_012_tags_45)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_012_tags_45[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P22_constr_45_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P22_45_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P22_specs_45_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P23_47_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2nodeConfigurationUpdate_e2ap_v1_01Acknowledge_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_013_tags_47[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P23_specs_47_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P23),
	offsetof(struct ProtocolIE_Container_1478P23, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_013 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_013_tags_47,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_013_tags_47)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_013_tags_47[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_013_tags_47,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_013_tags_47)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_013_tags_47[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P23_constr_47_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P23_47_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P23_specs_47_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P24_49_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2nodeConfigurationUpdate_e2ap_v1_01Failure_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_014_tags_49[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P24_specs_49_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P24),
	offsetof(struct ProtocolIE_Container_1478P24, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_014 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_014_tags_49,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_014_tags_49)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_014_tags_49[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_014_tags_49,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_014_tags_49)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_014_tags_49[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P24_constr_49_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P24_49_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P24_specs_49_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P25_51_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResetRequest_e2ap_v1_01IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_015_tags_51[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P25_specs_51_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P25),
	offsetof(struct ProtocolIE_Container_1478P25, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_015 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_015_tags_51,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_015_tags_51)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_015_tags_51[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_015_tags_51,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_015_tags_51)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_015_tags_51[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P25_constr_51_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P25_51_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P25_specs_51_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P26_53_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResetResponse_e2ap_v1_01IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_016_tags_53[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P26_specs_53_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P26),
	offsetof(struct ProtocolIE_Container_1478P26, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_016 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_016_tags_53,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_016_tags_53)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_016_tags_53[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_016_tags_53,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_016_tags_53)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_016_tags_53[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P26_constr_53_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P26_53_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P26_specs_53_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P27_55_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdate_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_017_tags_55[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P27_specs_55_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P27),
	offsetof(struct ProtocolIE_Container_1478P27, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_017 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_017_tags_55,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_017_tags_55)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_017_tags_55[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_017_tags_55,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_017_tags_55)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_017_tags_55[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P27_constr_55_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P27_55_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P27_specs_55_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P28_57_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2nodeConnected_ItemIEs_e2ap_v1_01,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_018_tags_57[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P28_specs_57_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P28),
	offsetof(struct ProtocolIE_Container_1478P28, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_018 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_018_tags_57,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_018_tags_57)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_018_tags_57[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_018_tags_57,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_018_tags_57)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_018_tags_57[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P28_constr_57_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P28_57_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P28_specs_57_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P29_59_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdate_e2ap_v1_01Acknowledge_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_019_tags_59[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P29_specs_59_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P29),
	offsetof(struct ProtocolIE_Container_1478P29, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_019 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_019_tags_59,
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_019_tags_59)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_019_tags_59[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_019_tags_59,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_019_tags_59)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P2_e2ap_v1_019_tags_59[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P29_constr_59_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P29_59_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P29_specs_59_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P30_61_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdate_e2ap_v1_01Failure_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_010_tags_61[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P30_specs_61_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P30),
	offsetof(struct ProtocolIE_Container_1478P30, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_010 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_010_tags_61,
	sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_010_tags_61)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_010_tags_61[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_010_tags_61,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_010_tags_61)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_010_tags_61[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P30_constr_61_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P30_61_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P30_specs_61_e2ap_v1_01	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_1478P31_63_e2ap_v1_01[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceQuery_e2ap_v1_01_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_011_tags_63[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_1478P31_specs_63_e2ap_v1_01 = {
	sizeof(struct ProtocolIE_Container_1478P31),
	offsetof(struct ProtocolIE_Container_1478P31, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_011 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v1_01_OF,
	asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_011_tags_63,
	sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_011_tags_63)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_011_tags_63[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_011_tags_63,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_011_tags_63)
		/sizeof(asn_DEF_ProtocolIE_Container_1478P3_e2ap_v1_011_tags_63[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_1478P31_constr_63_e2ap_v1_01,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_1478P31_63_e2ap_v1_01,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_1478P31_specs_63_e2ap_v1_01	/* Additional specs */
};

