/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "e42ap_v2_03.asn"
 * 	`asn1c -gen-APER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps`
 */

#include "ProtocolIE-Container.h"

#include "ProtocolIE-Field.h"
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P0_constr_1_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P1_constr_3_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P2_constr_5_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P3_constr_7_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P4_constr_9_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P5_constr_11_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P6_constr_13_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P7_constr_15_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P8_constr_17_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P9_constr_19_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P10_constr_21_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P11_constr_23_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P12_constr_25_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P13_constr_27_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P14_constr_29_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P15_constr_31_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P16_constr_33_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P17_constr_35_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P18_constr_37_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P19_constr_39_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P20_constr_41_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P21_constr_43_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P22_constr_45_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P23_constr_47_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P24_constr_49_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P25_constr_51_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P26_constr_53_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P27_constr_55_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P28_constr_57_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P29_constr_59_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P30_constr_61_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P31_constr_63_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P32_constr_65_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P33_constr_67_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P34_constr_69_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_2148P35_constr_71_e2ap_v2_03 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P0_1_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionRequest_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P0_e2ap_v2_03_tags_1_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P0_specs_1_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P0),
	offsetof(struct ProtocolIE_Container_2148P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P0_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P0_e2ap_v2_03_tags_1_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P0_e2ap_v2_03_tags_1_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P0_e2ap_v2_03_tags_1_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P0_e2ap_v2_03_tags_1_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P0_e2ap_v2_03_tags_1_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P0_e2ap_v2_03_tags_1_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P0_constr_1_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P0_1_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P0_specs_1_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P1_3_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionResponse_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_03_tags_3_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P1_specs_3_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P1),
	offsetof(struct ProtocolIE_Container_2148P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_03_tags_3_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_03_tags_3_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_03_tags_3_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_03_tags_3_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_03_tags_3_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_03_tags_3_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P1_constr_3_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P1_3_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P1_specs_3_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P2_5_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionFailure_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_03_tags_5_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P2_specs_5_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P2),
	offsetof(struct ProtocolIE_Container_2148P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_03_tags_5_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_03_tags_5_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_03_tags_5_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_03_tags_5_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_03_tags_5_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_03_tags_5_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P2_constr_5_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P2_5_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P2_specs_5_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P3_7_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteRequest_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_03_tags_7_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P3_specs_7_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P3),
	offsetof(struct ProtocolIE_Container_2148P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_03_tags_7_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_03_tags_7_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_03_tags_7_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_03_tags_7_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_03_tags_7_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_03_tags_7_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P3_constr_7_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P3_7_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P3_specs_7_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P4_9_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42RICsubscriptionRequest_e2ap_v2_03_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P4_e2ap_v2_03_tags_9_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P4_specs_9_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P4),
	offsetof(struct ProtocolIE_Container_2148P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P4_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P4_e2ap_v2_03_tags_9_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P4_e2ap_v2_03_tags_9_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P4_e2ap_v2_03_tags_9_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P4_e2ap_v2_03_tags_9_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P4_e2ap_v2_03_tags_9_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P4_e2ap_v2_03_tags_9_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P4_constr_9_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P4_9_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P4_specs_9_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P5_11_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42RICsubscriptionDeleteRequest_e2ap_v2_03_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P5_e2ap_v2_03_tags_11_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P5_specs_11_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P5),
	offsetof(struct ProtocolIE_Container_2148P5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P5_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P5_e2ap_v2_03_tags_11_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P5_e2ap_v2_03_tags_11_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P5_e2ap_v2_03_tags_11_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P5_e2ap_v2_03_tags_11_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P5_e2ap_v2_03_tags_11_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P5_e2ap_v2_03_tags_11_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P5_constr_11_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P5_11_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P5_specs_11_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P6_13_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteResponse_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P6_e2ap_v2_03_tags_13_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P6_specs_13_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P6),
	offsetof(struct ProtocolIE_Container_2148P6, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P6_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P6_e2ap_v2_03_tags_13_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P6_e2ap_v2_03_tags_13_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P6_e2ap_v2_03_tags_13_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P6_e2ap_v2_03_tags_13_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P6_e2ap_v2_03_tags_13_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P6_e2ap_v2_03_tags_13_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P6_constr_13_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P6_13_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P6_specs_13_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P7_15_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteFailure_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P7_e2ap_v2_03_tags_15_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P7_specs_15_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P7),
	offsetof(struct ProtocolIE_Container_2148P7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P7_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P7_e2ap_v2_03_tags_15_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P7_e2ap_v2_03_tags_15_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P7_e2ap_v2_03_tags_15_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P7_e2ap_v2_03_tags_15_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P7_e2ap_v2_03_tags_15_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P7_e2ap_v2_03_tags_15_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P7_constr_15_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P7_15_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P7_specs_15_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P8_17_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteRequired_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P8_e2ap_v2_03_tags_17_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P8_specs_17_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P8),
	offsetof(struct ProtocolIE_Container_2148P8, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P8_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P8_e2ap_v2_03_tags_17_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P8_e2ap_v2_03_tags_17_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P8_e2ap_v2_03_tags_17_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P8_e2ap_v2_03_tags_17_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P8_e2ap_v2_03_tags_17_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P8_e2ap_v2_03_tags_17_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P8_constr_17_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P8_17_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P8_specs_17_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P9_19_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICindication_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P9_e2ap_v2_03_tags_19_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P9_specs_19_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P9),
	offsetof(struct ProtocolIE_Container_2148P9, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P9_e2ap_v2_03 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P9_e2ap_v2_03_tags_19_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P9_e2ap_v2_03_tags_19_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P9_e2ap_v2_03_tags_19_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P9_e2ap_v2_03_tags_19_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P9_e2ap_v2_03_tags_19_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P9_e2ap_v2_03_tags_19_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P9_constr_19_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P9_19_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P9_specs_19_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P10_21_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolRequest_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_030_tags_21_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P10_specs_21_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P10),
	offsetof(struct ProtocolIE_Container_2148P10, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_030 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_030_tags_21_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_030_tags_21_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_030_tags_21_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_030_tags_21_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_030_tags_21_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_030_tags_21_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P10_constr_21_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P10_21_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P10_specs_21_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P11_23_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42RICcontrolRequest_e2ap_v2_03_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_031_tags_23_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P11_specs_23_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P11),
	offsetof(struct ProtocolIE_Container_2148P11, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_031 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_031_tags_23_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_031_tags_23_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_031_tags_23_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_031_tags_23_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_031_tags_23_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_031_tags_23_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P11_constr_23_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P11_23_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P11_specs_23_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P12_25_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolAcknowledge_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_032_tags_25_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P12_specs_25_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P12),
	offsetof(struct ProtocolIE_Container_2148P12, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_032 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_032_tags_25_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_032_tags_25_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_032_tags_25_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_032_tags_25_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_032_tags_25_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_032_tags_25_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P12_constr_25_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P12_25_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P12_specs_25_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P13_27_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolFailure_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_033_tags_27_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P13_specs_27_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P13),
	offsetof(struct ProtocolIE_Container_2148P13, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_033 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_033_tags_27_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_033_tags_27_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_033_tags_27_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_033_tags_27_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_033_tags_27_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_033_tags_27_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P13_constr_27_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P13_27_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P13_specs_27_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P14_29_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ErrorIndication_e2ap_v2_03_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_034_tags_29_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P14_specs_29_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P14),
	offsetof(struct ProtocolIE_Container_2148P14, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_034 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_034_tags_29_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_034_tags_29_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_034_tags_29_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_034_tags_29_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_034_tags_29_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_034_tags_29_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P14_constr_29_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P14_29_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P14_specs_29_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P15_31_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupRequest_e2ap_v2_03IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_035_tags_31_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P15_specs_31_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P15),
	offsetof(struct ProtocolIE_Container_2148P15, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_035 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_035_tags_31_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_035_tags_31_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_035_tags_31_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_035_tags_31_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_035_tags_31_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_035_tags_31_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P15_constr_31_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P15_31_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P15_specs_31_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P16_33_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42setupRequest_e2ap_v2_03IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_036_tags_33_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P16_specs_33_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P16),
	offsetof(struct ProtocolIE_Container_2148P16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_036 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_036_tags_33_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_036_tags_33_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_036_tags_33_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_036_tags_33_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_036_tags_33_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_036_tags_33_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P16_constr_33_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P16_33_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P16_specs_33_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P17_35_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupResponse_e2ap_v2_03IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_037_tags_35_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P17_specs_35_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P17),
	offsetof(struct ProtocolIE_Container_2148P17, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_037 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_037_tags_35_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_037_tags_35_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_037_tags_35_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_037_tags_35_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_037_tags_35_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_037_tags_35_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P17_constr_35_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P17_35_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P17_specs_35_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P18_37_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E42setupResponse_e2ap_v2_03IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_038_tags_37_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P18_specs_37_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P18),
	offsetof(struct ProtocolIE_Container_2148P18, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_038 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_038_tags_37_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_038_tags_37_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_038_tags_37_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_038_tags_37_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_038_tags_37_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_038_tags_37_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P18_constr_37_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P18_37_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P18_specs_37_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P19_39_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupFailure_e2ap_v2_03IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_039_tags_39_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P19_specs_39_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P19),
	offsetof(struct ProtocolIE_Container_2148P19, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_039 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_039_tags_39_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_039_tags_39_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_039_tags_39_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_039_tags_39_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_039_tags_39_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P1_e2ap_v2_039_tags_39_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P19_constr_39_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P19_39_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P19_specs_39_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P20_41_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2connectionUpdate_e2ap_v2_03_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_030_tags_41_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P20_specs_41_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P20),
	offsetof(struct ProtocolIE_Container_2148P20, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_030 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_030_tags_41_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_030_tags_41_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_030_tags_41_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_030_tags_41_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_030_tags_41_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_030_tags_41_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P20_constr_41_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P20_41_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P20_specs_41_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P21_43_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2connectionUpdate_e2ap_v2_03Ack_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_031_tags_43_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P21_specs_43_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P21),
	offsetof(struct ProtocolIE_Container_2148P21, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_031 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_031_tags_43_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_031_tags_43_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_031_tags_43_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_031_tags_43_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_031_tags_43_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_031_tags_43_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P21_constr_43_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P21_43_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P21_specs_43_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P22_45_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2connectionUpdate_e2ap_v2_03Failure_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_032_tags_45_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P22_specs_45_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P22),
	offsetof(struct ProtocolIE_Container_2148P22, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_032 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_032_tags_45_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_032_tags_45_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_032_tags_45_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_032_tags_45_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_032_tags_45_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_032_tags_45_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P22_constr_45_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P22_45_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P22_specs_45_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P23_47_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2nodeConfigurationUpdate_e2ap_v2_03_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_033_tags_47_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P23_specs_47_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P23),
	offsetof(struct ProtocolIE_Container_2148P23, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_033 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_033_tags_47_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_033_tags_47_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_033_tags_47_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_033_tags_47_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_033_tags_47_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_033_tags_47_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P23_constr_47_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P23_47_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P23_specs_47_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P24_49_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2nodeConfigurationUpdate_e2ap_v2_03Acknowledge_e2ap_v2_03_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_034_tags_49_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P24_specs_49_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P24),
	offsetof(struct ProtocolIE_Container_2148P24, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_034 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_034_tags_49_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_034_tags_49_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_034_tags_49_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_034_tags_49_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_034_tags_49_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_034_tags_49_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P24_constr_49_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P24_49_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P24_specs_49_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P25_51_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2nodeConfigurationUpdate_e2ap_v2_03Failure_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_035_tags_51_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P25_specs_51_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P25),
	offsetof(struct ProtocolIE_Container_2148P25, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_035 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_035_tags_51_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_035_tags_51_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_035_tags_51_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_035_tags_51_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_035_tags_51_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_035_tags_51_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P25_constr_51_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P25_51_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P25_specs_51_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P26_53_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResetRequest_e2ap_v2_03IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_036_tags_53_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P26_specs_53_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P26),
	offsetof(struct ProtocolIE_Container_2148P26, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_036 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_036_tags_53_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_036_tags_53_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_036_tags_53_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_036_tags_53_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_036_tags_53_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_036_tags_53_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P26_constr_53_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P26_53_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P26_specs_53_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P27_55_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResetResponse_e2ap_v2_03IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_037_tags_55_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P27_specs_55_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P27),
	offsetof(struct ProtocolIE_Container_2148P27, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_037 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_037_tags_55_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_037_tags_55_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_037_tags_55_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_037_tags_55_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_037_tags_55_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_037_tags_55_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P27_constr_55_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P27_55_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P27_specs_55_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P28_57_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdate_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_038_tags_57_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P28_specs_57_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P28),
	offsetof(struct ProtocolIE_Container_2148P28, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_038 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_038_tags_57_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_038_tags_57_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_038_tags_57_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_038_tags_57_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_038_tags_57_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_038_tags_57_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P28_constr_57_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P28_57_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P28_specs_57_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P29_59_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2nodeConnected_ItemIEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_039_tags_59_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P29_specs_59_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P29),
	offsetof(struct ProtocolIE_Container_2148P29, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_039 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_039_tags_59_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_039_tags_59_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_039_tags_59_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_039_tags_59_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_039_tags_59_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P2_e2ap_v2_039_tags_59_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P29_constr_59_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P29_59_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P29_specs_59_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P30_61_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdate_e2ap_v2_03Acknowledge_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_030_tags_61_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P30_specs_61_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P30),
	offsetof(struct ProtocolIE_Container_2148P30, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_030 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_030_tags_61_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_030_tags_61_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_030_tags_61_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_030_tags_61_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_030_tags_61_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_030_tags_61_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P30_constr_61_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P30_61_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P30_specs_61_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P31_63_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdate_e2ap_v2_03Failure_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_031_tags_63_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P31_specs_63_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P31),
	offsetof(struct ProtocolIE_Container_2148P31, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_031 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_031_tags_63_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_031_tags_63_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_031_tags_63_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_031_tags_63_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_031_tags_63_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_031_tags_63_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P31_constr_63_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P31_63_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P31_specs_63_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P32_65_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceQuery_e2ap_v2_03_IEs_e2ap_v2_03,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_032_tags_65_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P32_specs_65_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P32),
	offsetof(struct ProtocolIE_Container_2148P32, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_032 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_032_tags_65_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_032_tags_65_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_032_tags_65_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_032_tags_65_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_032_tags_65_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_032_tags_65_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P32_constr_65_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P32_65_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P32_specs_65_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P33_67_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2RemovalRequest_e2ap_v2_03IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_033_tags_67_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P33_specs_67_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P33),
	offsetof(struct ProtocolIE_Container_2148P33, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_033 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_033_tags_67_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_033_tags_67_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_033_tags_67_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_033_tags_67_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_033_tags_67_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_033_tags_67_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P33_constr_67_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P33_67_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P33_specs_67_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P34_69_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2RemovalResponse_e2ap_v2_03IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_034_tags_69_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P34_specs_69_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P34),
	offsetof(struct ProtocolIE_Container_2148P34, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_034 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_034_tags_69_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_034_tags_69_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_034_tags_69_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_034_tags_69_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_034_tags_69_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_034_tags_69_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P34_constr_69_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P34_69_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P34_specs_69_e2ap_v2_03	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_2148P35_71_e2ap_v2_03[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2RemovalFailure_e2ap_v2_03IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_035_tags_71_e2ap_v2_03[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_2148P35_specs_71_e2ap_v2_03 = {
	sizeof(struct ProtocolIE_Container_2148P35),
	offsetof(struct ProtocolIE_Container_2148P35, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_035 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_e2ap_v2_03_OF,
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_035_tags_71_e2ap_v2_03,
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_035_tags_71_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_035_tags_71_e2ap_v2_03[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_035_tags_71_e2ap_v2_03,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_035_tags_71_e2ap_v2_03)
		/sizeof(asn_DEF_ProtocolIE_Container_2148P3_e2ap_v2_035_tags_71_e2ap_v2_03[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ProtocolIE_Container_2148P35_constr_71_e2ap_v2_03,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_ProtocolIE_Container_2148P35_71_e2ap_v2_03,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_2148P35_specs_71_e2ap_v2_03	/* Additional specs */
};

